name: Docker Build

# Secrets that must be set in user repo:
#   - REGISTRY
#   - ACR_USERNAME
#   - ACR_PASSWORD

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/example-docker.yml"
      - "docker/example/**"

jobs:
  call-workflow:
    uses: comsysto/wp10-image-factory/.github/workflows/reusable-workflow-docker-image.yml@feature/image-factory-workflow-docker # change to main
    with:
      image-name: user-docker-example
      docker-dir: docker/example
      platform: arm64
    secrets: inherit
