name: Example Docker Build

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/example-docker.yml"
      - "docker/example/**"

env:
    REGISTRY: "wp10tfdevacr.azurecr.io"

jobs:
  call-workflow:
    uses: comsysto/wp10-image-factory/.github/workflows/reusable-workflow-docker-image.yml@feature/image-factory-workflow-docker
    with:
      image-name: silvija-test
      docker-dir: docker/example
      platform: arm64
      registry: ${{ env.REGISTRY }}
    secrets: inherit
