name: Packer Build - Linux

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/example-packer.yml"
      - "packer/example-linux/**"

jobs:
  call-workflow:
    uses: comsysto/wp10-image-factory/.github/workflows/reusable-workflow-packer-image.yml@feature/image-factory-workflow-docker # change to main
    with:
      image-name: user-packer-example
    secrets: inherit

# TODO