name: Example Docker Build

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/example-docker.yml"
      - "docker/example/**"

# without this trivy doesn't work - user should have their own credentials
# env:
  # AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  # AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  # AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  # AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"


jobs:
  call-workflow:
    uses: comsysto/wp10-image-factory/.github/workflows/reusable-workflow-docker-image.yml@feature/image-factory-workflow-docker
    with:
      image-name: silvija-test
      docker-dir: docker/example
      platform: arm64
      registry: "wp10tfdevacr.azurecr.io" # add comment
    secrets: inherit

